### ISSUE TITLE
Smart templates

### ISSUE THREAD

**Issue by markleusink** [Isometrica/isometrica-meteor#14]
* templates available for all Isometrica users
* can be imported into any instance (from the Smart Templates tab on the overview page)
* can be managed in a 'special' Isometrica instance

**Comment by SteveFortune** [comment]
I think we discussed 2 approaches to implementing the smart template repository:

- The `special` isa instance has a REST endpoint from which all instances will `GET` smart template
- Subscribing to a 'foreign' publication, i.e. an 'open source' installation of isa would subscribe to some sort of `smartTemplateCollection` which would be hosted on the `special` isa instance
