### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by sives** [Isometrica/isometrica-meteor#27]
It's not clear to the user how to search for a word in a document (it seems to default to Search and Replace, showing the Replace button, but what if I just want to search?)

**Comment by markleusink** [comment]
Changed the behavior of the search/replace function according to our discussion on this topic:
- User can enter a text in the search bar en click 'enter' to start a search
- The application then shows the search results
- In the search results, the 'replace' field is available. When a text is entered in that field, the 'replace' button becomes visible and the user can click it to replace the text in the 'contents' and 'title' field of all pages.
