### ISSUE TITLE
Copy and paste - getting spurious text 

### ISSUE THREAD

**Issue by sives** [Isometrica/isometrica-meteor#28]
When copying and pasting from a Word document, I'm seeing strange text getting inserted at the beginning of the document.

I copied and pasted the text from "Section 2 Understanding the organisation” in the document called Helen No 1 Management System Draft v1 into a new DocWiki page.

It pasted in fine, but after saving it I got some spurious characters appearing at the top.  I’ve attached a screenshot and a copy of the source document.

[Helen No 1 Management System Draft v1.docx](https://github.com/Isometrica/isometrica-meteor/files/33808/Helen.No.1.Management.System.Draft.v1.docx)

![screen shot 2015-11-13 at 09 04 21](https://cloud.githubusercontent.com/assets/2330529/11143147/f9422930-89ea-11e5-9f64-b6b4b7e6f966.png)

**Comment by markleusink** [comment]
Copied to Jira.
