### ISSUE TITLE
Performance problem on opening document

### ISSUE THREAD

**Issue by sives** [Isometrica/isometrica-meteor#29]
When opening the ISO 9001 Framework Manual document, it takes far too long - about 8 seconds on my MacBook Pro running Safari.  There is also a strange UI transition - first of all the DocWiki icons on the workspace are duplicated (from 2 to 4), then a coloured cursor spinner appears, then the document opens.   

At the same time, I'm getting high CPU usage showing in my Mac Activity Monitor, and the fan comes on.

Hopefully we can get the lag time down to a second or less and get rid of the high CPU usage/fan triggering.  If there is any greater lag than this, we need to show some kind of progress indicator to show that the system is working, and hasn't just crashed.

**Comment by sives** [comment]
Some more feedback on this issue.  When I tested again today on my MacBook Pro running Yosemite 10.10.5 and Safari 8.0.8, I still get the duplication of the Docwiki icon panels, but no high CPU usage.   When I tested on my iPad running iOS 9.1, the document actually opened fairly fast - in a couple of seconds - with no icon duplication beforehand.

**Comment by markleusink** [comment]
@sives I wasn't able to reproduce the same issue that you were seeing, but I found a possible issue in the code. I made some changes that I just uploaded to demo.isometrica.io. Can you run a quick check to see if that helped?

**Comment by sives** [comment]
@markleusink  On the positive side, the document now loads faster and I don't see the rotating spinner any more.  On the negative side, I still see the duplication of the icon panels just prior to the document opening.  So that's progress, of a sort.  Fingers crossed we can find the cause of the duplication.  Is there anything I can do from my end to help pin this down?

**Comment by markleusink** [comment]
On hold until the DocWiki has been rewritten as a module (scheduled for next Monday)

**Comment by markleusink** [comment]
Related issue: #37

**Comment by markleusink** [comment]
Copied to Jira.
