### ISSUE TITLE
Deleting documents - missing UI

### ISSUE THREAD

**Issue by sives** [Isometrica/isometrica-meteor#38]
The system needs to prompt you to confirm your deletion request.  The deletion confirmation dialog needs to be better positioned (in the centre of the screen? - need to check placement rule with Jack)

The dialog needs expanding to something like:

["Document name"] has been deleted. You can recover this document from the Deleted & Archived tab.

**Comment by markleusink** [comment]
Added a confirmation dialog. Updated the dialog text.

I'll leave the dialog positioning issue to Jack.

**Comment by markleusink** [comment]
Copied to Jira.
