### ISSUE TITLE
User message should be clearer when comparing pages

### ISSUE THREAD

**Issue by sives** [Isometrica/isometrica-meteor#41]
When providing feedback to the user on comparing 2 different versions of a page, refer to (v2) and (v3) rather than simply (2) and (3) - see attached screenshot.  In the current message, users may think the numbers are page numbers.

![screen shot 2015-12-10 at 14 06 29](https://cloud.githubusercontent.com/assets/2330529/11717289/6ae6ca98-9f47-11e5-8281-f575edac7de6.png)

**Comment by markleusink** [comment]
Fixed in development version, needs to be deployed to demo server (need to discuss that with Michael)
